// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qz82g6YFD3ByaFAf5Je7H9
// Component: x5CQBu2cJl
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import LinkItem from "../../LinkItem"; // plasmic-import: qkHzGyBKg8/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: qz82g6YFD3ByaFAf5Je7H9/projectcss
import * as sty from "./PlasmicMenu.module.css"; // plasmic-import: x5CQBu2cJl/css

export const PlasmicMenu__VariantProps = new Array();

export const PlasmicMenu__ArgProps = new Array();

function PlasmicMenu__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <ul
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.ul, projectcss.root_reset, sty.root)}
    >
      <LinkItem className={classNames("__wab_instance", sty.linkItem__nw0G)} />

      <LinkItem className={classNames("__wab_instance", sty.linkItem__e5HN)} />

      <LinkItem className={classNames("__wab_instance", sty.linkItem__uVaZe)} />

      <LinkItem className={classNames("__wab_instance", sty.linkItem__hUDbK)} />
    </ul>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMenu__ArgProps,
      internalVariantPropNames: PlasmicMenu__VariantProps
    });

    return PlasmicMenu__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMenu";
  } else {
    func.displayName = `PlasmicMenu.${nodeName}`;
  }
  return func;
}

export const PlasmicMenu = Object.assign(
  // Top-level PlasmicMenu renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicMenu
    internalVariantProps: PlasmicMenu__VariantProps,
    internalArgProps: PlasmicMenu__ArgProps
  }
);

export default PlasmicMenu;
/* prettier-ignore-end */
